#!/usr/bin/perl -w

# Reading a single character at a time.
print "Enter y or n: ";
my $answer = getc;
print "you entered $answer\n";

# Read 7 characters from each line in /etc/shells;
# ignore commented out lines

# --- FIXME -------

#my $infile = '/etc/shells';
#open(FILE, $infile) || die "unable to open $infile :$!\n";
#
#while( read(FILE, $line, 7) ) {
#   next if ($line =~ /^#/);
#   print "$line\n";
#}
#
#close FILE;

